services:
  backend:
    build:
      context: ./backend
      target: production
    container_name: media-server-backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend/media:/app/media
      - ./backend/database.sqlite:/app/database.sqlite
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - PORT=3000
      - TMDB_API_KEY=MY_TMDB_API_KEY
      - JWT_PRIVATE_KEY=MySecretKey
      - THUMBNAILS_PATH=media/thumbnails/
      - ADMIN_USER=admin
      - ADMIN_PASSWORD=admin
  frontend:
    build:
      context: ./frontend
      target: production
    container_name: media-server-frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - BASE_URL=http://backend:3000
    depends_on:
      - backend
